{
  // Generated by Terraform from wrangler.jsonc.tpl — do not edit directly.
  // Edit wrangler.jsonc.tpl and re-run terraform apply.
  "name": "tf-cf-wanstats",
  "main": "src/index.ts",
  "compatibility_date": "2025-01-01",
  "account_id": "${account_id}",
  "workers_dev": true,
  "triggers": {
    "crons": ["*/5 * * * *"]
  },
  "d1_databases": [
    {
      "binding": "DB",
      "database_name": "tf-cf-wanstats-metrics",
      "database_id": "${d1_database_id}"
    }
  ],
  "vars": {
    "ACCOUNT_ID": "${account_id}"
  }
}
