{
  // Generated by Terraform from wrangler.jsonc.tpl — do not edit directly.
  // Edit wrangler.jsonc.tpl and re-run terraform apply.
  "name": "tf-cf-wanstats",
  "main": "src/index.ts",
  "compatibility_date": "2025-01-01",
  "account_id": "${account_id}",
  "workers_dev": true,
  "triggers": {
    "crons": ["*/5 * * * *"]
  },
  // The midnight run re-reads a month of R2 CSVs for billing p95 (~14M lines
  // at 2000 tunnels); the default 30 s CPU budget is too tight for that.
  // 300000 is the Workers Paid maximum.
  "limits": {
    "cpu_ms": 300000
  },
  "d1_databases": [
    {
      "binding": "DB",
      "database_name": "tf-cf-wanstats-metrics",
      "database_id": "${d1_database_id}"
    }
  ],
  "r2_buckets": [
    {
      "binding": "RAW_METRICS",
      "bucket_name": "tf-cf-wanstats-raw-metrics"
    }
  ],
  "vars": {
    "ACCOUNT_ID": "${account_id}"
  }
}
